### ISSUE TITLE
Authorize Users with Google

### ISSUE THREAD

**Issue by chadlagore** [chadlagore/beluga#6]
# Authorize Users

+ Use Google for now.
+ Later facebook.

**Comment by agentfll** [comment]
Implement authentication with Google accounts.

This ticket includes a small amount of design work related to mechanisms for communication between the server and the client application for indicating authentication success or failure, and for providing identity data (specifically a bearer token).

This ticket includes, but is not limited to, the POST /sessions/google endpoint.

**Comment by agentfll** [comment]
Addressed by #60
